### PR TITLE
Add Feedback form link

### PR DESCRIPTION
**Pull request by edwinzhng**
image

### CODE REVIEW

**Comment by rodrigonogueira4** [comment]
Maybe just "Feedback" instead of "Give Feedback"?

**Comment by edwinzhng** [comment]
> Maybe just "Feedback" instead of "Give Feedback"?

Sure works for me

**Comment by lintool** [comment]
I like just "Feedback" - also, add a tiny bit more space on the right rail, e.g., move text a bit over to the left.

**Comment by lintool** [comment]
Alternatively, what about the Boostrap envelope glyphicon?
https://getbootstrap.com/docs/3.3/components/

first row, second from right?

**Comment by edwinzhng** [comment]
Updated with just "Feedback", not sure if any of the icons really indicates feedback clearly

**Comment by edwinzhng** [comment]
> I like just "Feedback" - also, add a tiny bit more space on the right rail, e.g., move text a bit over to the left.

did you mean the alignment? I just didn't screenshot the full page

**Comment by lintool** [comment]
> > I like just "Feedback" - also, add a tiny bit more space on the right rail, e.g., move text a bit over to the left.
> 
> did you mean the alignment? I just didn't screenshot the full page. new screenshot is of the entire page

Ah okay!

**Pull request merged**
